#
###################################
# Site wide configuration
####################################
#
title:       "Jiang Pz's blog"
description: 'A backend developer who loves design awesome things. Working for CTVIT in Beijing, China.'
url:         #'http://jiangpz.github.io'

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Jiang Pz"
  avatar: avatar.jpg
  job: "J2EE Developer"
  bio: "A backend developer who loves design awesome things. Working for DHCC in Beijing, China."
  email: jiangpeizhao@outlook.com
  disqus-shortname: jiangpzgithubio
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jiangpz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: NewSaga #username
  flickr: #username
  codepen: #username
